### ISSUE TITLE
Dynamic Series Update

### ISSUE THREAD

**Issue by meersel** [dreamRs/apexcharter#28]
HI,

Does R Apexcharter support the **Dynamic Series Update** functionality (see example: https://github.com/apexcharts/apexcharts.js) ?
If so,  could you provide me with an example how to use this with the R apexcharter package functions ?

Thanks in advance.

Miguel

**Comment by pvictor** [comment]
Hello Miguel,

There's some possibilities in Shiny through proxy or auto-update method, and you can retrieve click on charts as inputs values.

Example of charts automatically updated: https://github.com/dreamRs/apexcharter/blob/master/examples/real-time.R

Examples for clicking chart can be launched with `run_demo_input("click")`.

The example [here](https://apexcharts.com/javascript-chart-demos/column-charts/dynamic-loaded-chart/) from official documentation is a little more complex since it requires lot of custom JavaScript code.

Victor
